### ISSUE TITLE
Segmentation fault when beginning video playback because VLC tries to start its own lua interpreter

### ISSUE THREAD

**Issue by gcr** [luapower/libvlc#1]
Lua isn't reentrant. Since VLC has its own Lua plugin and links separately with liblua, VLC crashes when trying to create its own lua interpreter because we already have an interpreter running with some global state. How did you disable VLC's Lua plugin to get libvlc working?

I am on Linux, using `VLC media player 2.1.5 Rincewind (revision 2.1.4-49-gdab6cb5)`, and `LuaJIT 2.0.3`.

Minimal crashing example:

```
local ffi = require'ffi'
require 'libvlc_h'
local vlc = ffi.load 'libvlc'

vlc_inst = vlc.libvlc_new(0, nil)
vlc_m = vlc.libvlc_media_new_path(vlc_inst, "/home/michael/The Wind Rises.mkv")
vlc_mp = vlc.libvlc_media_player_new_from_media(vlc_m)
vlc.libvlc_media_release(vlc_m)
vlc.libvlc_video_set_format(vlc_mp, "RV16", 300, 300, 600)
vlc.libvlc_media_player_play(vlc_mp)
```

Backtrace in GDB, showing VLC starting to load the lua plugin and failing. (if it would help, i can recompile VLC with debug symbols but i'm pretty sure this is a lua problem or a simple "VLC Lua plugin" issue)

```
$ gdb luajit
GNU gdb (GDB) 7.8.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from luajit...(no debugging symbols found)...done.
"/store/home/michael/Projects/subtitle-drills/love-test/vlc-test.lua" is not a core dump: File format not recognized
(gdb) run
Starting program: /usr/bin/luajit 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> require("vlc-test")
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
    add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/home/michael/.gdbinit".
To completely disable this security protection add
    set auto-load safe-path /
line to your configuration file "/home/michael/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
    info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
> [New LWP 11000]

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 11000]
0x000000000042a78a in ?? ()
(gdb) bt
#0  0x000000000042a78a in ?? ()
#1  0x000000000044718a in lua_rawset ()
#2  0x00007fffdf08837f in ?? () from /usr/lib/vlc/plugins/lua/liblua_plugin.so
#3  0x00007fffdf0885b5 in ?? () from /usr/lib/vlc/plugins/lua/liblua_plugin.so
#4  0x00007fffdf08af80 in ?? () from /usr/lib/vlc/plugins/lua/liblua_plugin.so
#5  0x00007ffff6e91995 in ?? () from /usr/lib/libvlccore.so.7
#6  0x00007ffff6e91f4e in vlc_module_load () from /usr/lib/libvlccore.so.7
#7  0x00007ffff6e5bb52 in ?? () from /usr/lib/libvlccore.so.7
#8  0x00007ffff6e5e77c in ?? () from /usr/lib/libvlccore.so.7
#9  0x00007ffff6e61cc6 in ?? () from /usr/lib/libvlccore.so.7
#10 0x00007ffff6578374 in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007ffff740127d in clone () from /usr/lib/libc.so.6
(gdb) 
```

I can't find any way to disable the lua plugin in VLC's command line options. Removing `/usr/lib/vlc/plugins/lua/liblua_plugin.so` fixes the crash, but I certainly can't ask my users to do that.

**Comment by capr** [comment]
The idea with luapower is to ship all binaries yourself with the app so that you can control stuff like what you just mentioned, and not have your app crash on different user environments. I know this is not the way people do it in Linux, but I think shipping apps over system-provided libraries is a disaster (hence inventions like docker). You can barely depend on glibc (I would even ship that if I had a choice). So my answer would be -- build and ship VLC yourself with your app if you can.

Normally, I provide binaries and build scripts in the repo directly (see just about any other library in here), but with VLC I didn't do that because they (used to?) change too fast and I don't have time right now to keep them up-to-date in luapower. Basically, libvlc needs a maintainer.

Sorry if I can't be of more help right now. I hope that this clarifies the situation somewhat.

**Comment by gcr** [comment]
Aha; I see. So to avoid this issue, the proper thing would be to distribute a custom version of VLC that happens not to contain the VLC Lua plugin.

That makes sense. Many thanks for the clarification!
